version: '3'

services:
  db:
    container_name: postgresql-dev
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - pgdata:/var/lib/postgresql/data
  app: 
    build: . ## use Dockerfile
    depends_on: 
      db:
        condition: service_healthy  
    command: yarn dev
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app ## monitoro a pasta atual . e envio as alterações para /usr/app
volumes:
    pgdata: